AllCops:
  RunRailsCops: true
  Exclude:
   - 'bin/*'
   - 'app/controllers/exception_handler/exception_controller.rb'

Metrics/LineLength:
  Max: 150
  AllowURI: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/PredicateName:
  NamePrefixBlacklist:
    - get_
    - set_
