Rails:
  Enabled: true
AllCops:
  Exclude:
    - 'bin/*'
    - 'app/controllers/exception_handler/exception_controller.rb'
    - 'script/benchmark'
Metrics/LineLength:
  Max: 150
  AllowURI: true
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/PredicateName:
  NamePrefixBlacklist:
    - get_
    - set_
Style/StringLiterals:
  EnforcedStyle: double_quotes
Metrics/MethodLength:
  Max: 5
Metrics/ClassLength:
  Max: 150
Metrics/ParameterLists:
  Max: 4
Style/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/AndOr:
  EnforcedStyle: conditionals
Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Style/BlockDelimiters:
  EnforcedStyle: semantic
  Exclude:
    - factories/**/*
Style/FrozenStringLiteralComment:
  Enabled: false
Rails/HttpPositionalArguments: # Breaks unless Rails 5
  Enabled: false
Style/VariableNumber:
  Enabled: false
