default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

production:
  <<: *default
  database: wordofmouth
  username: wordofmouth
  password: wordofmouth

development:
  <<: *default
  database: wordofmouth_development
  username: wordofmouth
  password: wordofmouth

test: &test
  <<: *default
  database: wordofmouth_test
  username: wordofmouth
  password: wordofmouth


cucumber:
  <<: *test
